//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokRamil.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountInPackage { get; set; }
        public string UnitOfMeasurement { get; set; }
        public Nullable<int> CountInWarehourse { get; set; }
        public Nullable<int> MinRemainder { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> ID_type { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
