//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokRamil.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public int ID { get; set; }
        public Nullable<int> ID_prod { get; set; }
        public Nullable<int> ID_mat { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}
