//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokRamil.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Article { get; set; }
        public Nullable<int> MinCost { get; set; }
        public string Image { get; set; }
        public Nullable<int> PeopleCount { get; set; }
        public Nullable<int> ShopNumber { get; set; }
        public Nullable<int> ID_type { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TypeProduct TypeProduct { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
